---
apiVersion: v1
data:
  asmita.conf: |
    This is my configuration file...asmita here !!
kind: ConfigMap
metadata:
  name: config-asmita

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-am
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4xMjM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment 
  labels:
    app: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: sandhyadockerac/react-app:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: testconfigmap
              mountPath: /tmp/config
            - name: testsecret
              mountPath: /tmp/mysecrets
      volumes:
        - name: testconfigmap
          configMap:
            name: config-asmita
            items:
              - key: asmita.conf
                path: asmita.conf
        - name: testsecret
          secret:
            secretName: secret-am

---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 500
      targetPort: 3000
    

