---
apiVersion: v1
data:
  sandhya.conf: |
    This is my configuration file...sandhya here !!
kind: ConfigMap
metadata:
  name: config-sandhya

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-sa
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4xMjM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment 
  labels:
    app: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: sandhyadockerac/react-app:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: testconfigmap
              mountPath: /tmp/config
            - name: testsecret
              mountPath: /tmp/mysecrets
      volumes:
        - name: testconfigmap
          configMap:
            name: config-sandhya
            items:
                - key: sandhya.conf
                path: sandhya.conf
        - name: testsecret
          secret:
            secretName: secret-sa

---
apiVersion: v1
kind: Service
metadata:
  name: service-react-app
spec:
  selector:
    app: react-app
  type: Nodeport
  ports:
    - protocol: TCP
      port: 500
      targetPort: 3000
     
    

